#!/usr/bin/env python3
import os
import sys
from pathlib import Path

def complete_path(path):
    host_prefix = os.getenv('WORKSPACE_HOST_PATH', '')
    ws_mnt = Path(os.getenv('WORKSPACE_HOME', '/workspace'))
    fake_part_of_path = ws_mnt.parents[0]
    host_relative_path = path.relative_to(fake_part_of_path)
    return str (host_prefix / host_relative_path)  

if __name__ == '__main__':
    for a in sys.argv[1:]:
        print(complete_path(Path(a)))
