#!/bin/python3
import os
import sys
import subprocess
from switch_mount import substitution_file as sf

if __name__ == '__main__':
    tmp_path = None
    try:
        idx = sys.argv.index('-f') + 1
        tmp_path = sys.argv[idx] + '.tmp'
        sf(sys.argv[idx], new_path=tmp_path)
        sys.argv[idx] = tmp_path
    except:
        print('doesn\'t find dockerfile')
    sys.argv[0] = '/usr/bin/docker'
    os.system(' '.join(sys.argv))
